#!/usr/bin/env bash

export NETWORK_LOCATION="$(/usr/sbin/scselect 2>&1 | egrep '^ \* ' | sed 's:.*(\(.*\)):\1:')"

if [ "$NETWORK_LOCATION" = "BBC On Network" ]; then
  if [[ "$1" == "localhost" || "$1" == "127.0.0.1" || "$1" =~ "192.168" || "$1" =~ "sandbox.dev.bbc.co.uk" || "$1" =~ "sandbox.bbc.co.uk" ]]; then
    nc -X 5 $1 $2
  else
    nc -x "socks-gw.reith.bbc.co.uk:1085" -X 5 $1 $2
  fi
else
    nc -X 5 $1 $2
fi
