#!/usr/bin/env bash

s3cp() {
  if [ "$3" == "live" ] ; then
    BUCKET='live-galileo-interface-mt-resources-inputbucket-5nfo4tjd8049'
    PROFILE='media-tools-prod'
  fi
  if [ "$3" == "test" ] ; then
    BUCKET='test-galileo-interface-mt-resources-inputbucket-3z3olim0ng99'
    PROFILE='media-tools-dev'
  fi
  if [ "$3" == "int" ] ; then
    BUCKET='int-galileo-interface-mt-resources-inputbucket-i3g48dkvmuft'
    PROFILE='media-tools-dev'
  fi
    
  aws s3 cp s3://$BUCKET/$1 $2 --profile $PROFILE
}

export AWS_ACCOUNT_NUMBER=169163488685
export AWS_DEFAULT_REGION=eu-west-1
export AWS_ACCESS_KEY_ID=
export AWS_ACCOUNT_NAME=cps
export AWS_SECRET_ACCESS_KEY=

alias aws:clear="unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY"
alias aws:env="env | grep AWS"