#!/usr/bin/env bash

export SERVER_ENV=dev
export CERT_LOCATION=$HOME/.certs/dev.bbc.co.uk.p12
export CERT_PASSPHRASE=dev.bbc.co.uk

# Generic Cert Locations
export CERTS_LOCATION=$HOME/.certs
export COMBINED_DEV_CERT_PEM=$CERTS_LOCATION/dev.bbc.co.uk.pem
export CA_BUNDLE=$CERTS_LOCATION/ca-bundle.crt
export DEV_CERT_PEM=$CERTS_LOCATION/dev.bbc.co.uk.pem
export DEV_CERT_P12=$CERTS_LOCATION/dev.bbc.co.uk.p12
export DEV_CERT_P12_PASSWORD=dev.bbc.co.uk
export DEV_CERT_P12_PASSWORD=$CERT_PASSPHRASE

export COSMOS_CERT_KEY=$CERT_LOCATION/dev.bbc.co.uk.key
export COSMOS_CERT=$DEV_CERT_PEM
export COSMOS_CA=$CA_BUNDLE

# Test Related
export navigator_cert=$DEV_CERT_PEM
export BBC_P12_KEY=$DEV_CERT_P12:$DEV_CERT_P12_PASSWORD
export CA_CLOUD=$CERTS_LOCATION/cloud-ca.pem
export CERT_PATH=$DEV_CERT_P12
export CERT_PASS=$DEV_CERT_P12_PASSWORD

