#!/usr/bin/env bash

# Cosmos login Aliases

pythonLogin(){
  $HOME/workspace/cosmos-tooling/cosmos.py $2 $1 $3
}

alias cssh='$HOME/workspace/cosmos-tooling/cosmos.py'

alias issh='pythonLogin $1 int $2'
alias tssh='pythonLogin $1 test $2'
alias lssh='pythonLogin $1 live $2'