#!/usr/bin/env bash

# Git aliases
alias g:s="git status"
alias g:d="git diff"
alias g:f="git fetch"
alias g:pom="git pull origin master"
alias g:p="git push origin HEAD"
alias g:c="git commit -am"
alias g:l="git log"
alias g:rc="git rebase --continue"
alias g:r="git rebase -i HEAD~"
alias g:remote="git fetch origin && git reset --hard origin/master"
alias g:pull="git pull origin $(git branch | grep -E '^\* ' | sed 's/^\* //g')"
# reguired for GPG
export GPG_TTY=$(tty)
export GITHUB_ACCESS_TOKEN=
alias g:help="echo \"\ng:s: git status\ng:d: git diff\ng:f: git fetch\ng:pom: git pull origin master\ng:p: git push current branch\ng:l: git log\""
