#!/usr/bin/env bash

export SERVER_ENV=dev

export JAVA_PROXY_OPTS="-Dhttp.useProxy=true
-Dhttp.proxyHost=www-cache.reith.bbc.co.uk
-Dhttp.proxyPort=80
-Dhttps.proxyHost=www-cache.reith.bbc.co.uk
-Dhttps.proxyPort=80
-Dhttp.nonProxyHosts=localhost|pal.sandbox.dev.bbc.co.uk
-Dhttps.nonProxyHosts=localhost|pal.sandbox.dev.bbc.co.uk"

# Java configuration
export PLATFORM_JAVA_OPTS="$DEV_CERT_JAVA_OPTS
  -Djsse.enableSNIExtension=false
  -Duser.timezone=UTC"

# Maven configuration
export MAVEN_OPTS="$PLATFORM_JAVA_OPTS
    -Xms256m -Xmx512m
    -Denv.keyStore=$DEV_CERT_P12
    -Denv.keyStoreType=PKCS12
    -Denv.keyStorePassword=$CERT_PASSPHRASE"

export SBT_OPTS="$MAVEN_OPTS -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=512m"
