#!/usr/bin/env bash

export SERVER_ENV=dev

export JAVA_PROXY_OPTS="-Dhttp.useProxy=true
-Dhttp.proxyHost=www-cache.reith.bbc.co.uk
-Dhttp.proxyPort=80
-Dhttps.proxyHost=www-cache.reith.bbc.co.uk
-Dhttps.proxyPort=80
-Dhttp.nonProxyHosts=localhost|pal.sandbox.dev.bbc.co.uk
-Dhttps.nonProxyHosts=localhost|pal.sandbox.dev.bbc.co.uk"

# Java configuration
export PLATFORM_JAVA_OPTS="-Djavax.net.ssl.keyStore=$DEV_CERT_P12
  -Djavax.net.ssl.trustStore=$CERTS_LOCATION/jssecacerts
  -Djsse.enableSNIExtension=false
  -Duser.timezone=UTC"

# Maven configuration
export MAVEN_OPTS="$PLATFORM_JAVA_OPTS
    -Xms256m -Xmx512m
    -Denv.keyStore=$DEV_CERT_P12
    -Denv.keyStoreType=PKCS12
    -Denv.keyStorePassword=$CERT_PASSPHRASE"

export SBT_OPTS="$MAVEN_OPTS -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=512m"

# -- http://www.jayway.com/2014/01/15/how-to-switch-jdk-version-on-mac-os-x-maverick/
#    Example use: setjdk 1.7 - selects the latest installed JDK version of the 1.7 branch
#    Example use: setjdk 1.7.0_51 - select a specific version
#    Run /usr/libexec/java_home -h to get more details on how to choose versions
function setjdk() {
  if [ $# -ne 0 ]; then
    removeFromPath '/System/Library/Frameworks/JavaVM.framework/Home/bin'
    if [ -n "${JAVA_HOME+x}" ]; then
      removeFromPath $JAVA_HOME
    fi
    export JAVA_HOME=`/usr/libexec/java_home -v $@`
    export PATH=$JAVA_HOME/bin:$PATH
  fi
}
function removeFromPath() {
  export PATH=$(echo $PATH | sed -E -e "s;:$1;;" -e "s;$1:?;;")
}

export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)