#!/usr/bin/env bash

export keypairId=
export private_key_string=
export AWS_ACCESS_KEY_ID=
export AWS_ACCOUNT_NAME=cps
export AWS_SECRET_ACCESS_KEY=
export ASSET_NOTIFICATIONS_QUEUE=https://sqs.eu-west-1.amazonaws.com/169163488685/dev-barrop02-optimo-asset-notifications
export ENVIRONMENT=dev

export FEATURE_TOGGLES='{}'
alias optimo="cd $HOME/workspace/optimo && yarn run start:dev"