#!/usr/bin/env bash

addWormholeAccess(){
  if [ $2 = "prod" ] ; then
    AWS_ACCOUNT_NUMBER=303748928824
  fi
  if [ $2 = "dev" ] ; then
    AWS_ACCOUNT_NUMBER=169163488685
  fi
  cd $HOME/workspace/multi-account-infrastructure && ./admin allow-user $AWS_ACCOUNT_NUMBER $1 AdministratorAccess && cd -
}

alias addToProd="addWormholeAccess $1 prod"
alias addToDev="addWormholeAccess $1 dev"
